openapi: 3.0.0
info:
  version: 1.0.0
  title: 클릭소프트 연동 API
  description: 클릭소프트 웹 앱 연동 API
  license:
    name: kaburi
servers:
  - url: http://localhost:4020/
components:
  #Schemas : model 정보
  schemas:
    ErrorResult:
      type: object
      properties:
        message:
          type: string
        error:
          type: object
          additionalProperties:
            type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorsResult'

    ErrorsResult:
      type: object
      properties:
        path:
          type: array
          items:
            type: string
        pathKey:
          type: string 
  responses:
    successResponse:
      description: successful request with no data
      content:
        application/json:
          schema:
            type: object
            example: { 'status': 200, 'success': true, 'message': 'message' }
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResult'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResult'
          example:
            success: false
            message: 서버 내부 오류
#Paths api 경로 지정
paths:
  /api/clickdesk/doctor/:
    $ref: './clickdesk/doctor.yaml#/~1'
  /api/clickdesk/doctor/{id}:
    $ref: './clickdesk/doctor.yaml#/~1{id}'
  /api/clickdesk/doctor/seq:
    $ref: './clickdesk/doctor.yaml#/~1seq'

  /api/clickdesk/reason:
    $ref: './clickdesk/reason.yaml#/~1'

  # api/users
  /api/users/{userId}/add-svcs:
    $ref: './users/users.yaml#/~1users~1{userId}~1add-svcs'
 
